room_layout_config= [
    {
        "room_key": "church_interior",
        "description": "A small, one room church with pews and an altar. A small book lays upon the altar. Path: ",
        "description_itemless": "A small, one room church with pews and an altar.",
        "starting_room": False,
        "north_room_key": "church",
        "south_room_key": None,
        "west_room_key": None,
        "east_room_key": None,
        "item": "Book",
    },
    {
        "room_key": "church",
        "description": "There is a small church ahead. Laying beside the door is a shovel. Paths: ",
        "description_itemless": "There is a small church ahead. Paths: ",
        "starting_room": False,
        "north_room_key": "obelisk",
        "south_room_key": "church_interior",
        "west_room_key": None,
        "east_room_key": None,
        "item": "shovel"
    },
    {
        "room_key": "garden",
        "description": "A garden of various flowers. In the center is a white rose. Path: ",
        "description_itemless": "A garden of various roses. Path: ",
        "starting_room": False,
        "north_room_key": None,
        "south_room_key": "obelisk",
        "west_room_key": None,
        "east_room_key": None,
        "item": "Rose",
    },
    {
        "room_key": "obelisk",
        "description": "Before you stands the Obelisk. Surrounding it are several statues of people. Paths: ",
        "description_itemless": "Before you stands the Obelisk. Surrounding it are several statues of people. Paths: ",
        "starting_room": True,
        "north_room_key": "garden",
        "south_room_key": "church",
        "west_room_key": "mountainside",
        "east_room_key": "theater",
        "item": "Door",
    },
    {
        "room_key": "theater",
        "description": "An ampitheater, staged in front of the ocean. Laying on the stage is a key. Path: ",
        "description_itemless": "An ampitheater, staged in front of the ocean. Path: ",
        "starting_room": False,
        "north_room_key": None,
        "south_room_key": None,
        "west_room_key": "obelisk",
        "east_room_key": None,
        "item": "Key",
    },
    {
        "room_key": "mountainside",
        "description": "Standing above you is a large mountain. A small campfire is lit at the base. Path: ",
        "description_itemless": "Standing above you is a large mountain. The campfire is nothing but ash. Path: ",
        "starting_room": False,
        "north_room_key": None,
        "south_room_key": None,
        "west_room_key": None,
        "east_room_key": "obelisk",
        "item": "fire",
    }
]